config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/login'
  get 'home/logout'
  get 'home/register'
  get 'application/client_authorization'

  resources :offers, only: %i[index show] do
    post '/accept', to: 'offers#accept', :on => :member
    post '/reject', to: 'offers#reject', :on => :member
  end

  resources :customers, only: %i[show create new update edit]
  resources :products, only: %i[index]

  namespace :rest do
    resources :offers, only: [] do
      resources :products, only: %i[index show create]
    end

    resources :products, only: [] do
      resources :type_attributes, only: %i[index show create]
    end

    resources :users, param: :id, only: %i[index show create]
    resources :customers, param: :id, only: %i[index show create] do
      resources :offers, only: %i[index show create]
      post 'offers/:id/accept', to: 'offers#accept'
      post 'offers/:id/reject', to: 'offers#reject'
    end
  end
    post '/auth/login_user', to: 'authentication#login_user'
    post '/auth/login_customer', to: 'authentication#login_customer'
end

app/controllers/home_controller.rb
# frozen_string_literal: true

# app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in

  def index
    @customer = customer if logged_in
    @product_attrs = Settings.product_type_attributes
  end

  def login; end

  def logout
    if logged_in
      logout_client
      redirect_to home_login_path, flash: { success: I18n.t(:successfully_logout, scope: 'locale.messages') }
    else
      flash.now[:notice] = I18n.t(:not_logged_in, scope: 'locale.messages')
      render action: :login
    end
  end

  def register; end

  private

  def customer
    @customer ||= authorize_client_request
  end

  def logged_in
    @logged_in = logged_in?
  end
end

app/views/home/index.html.erb
<%= render "layouts/header" %>
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
  <div class="container-fluid">
    <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if @logged_in %>
            <%= link_to t(:logout, scope: 'locale.messages'), home_logout_path %>
          <% else %>
            <%= link_to t(:login, scope: 'locale.messages'), home_login_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content index_background">
  <div class="container-fluid">
    <h2><%= t(:available_packages, scope: 'locale.messages') %></h2>
    <div class="row">
      <div class="index_package">
        <% if @product_attrs %>
          <% @product_attrs.each do |p| %>
            <div class="package_image"><%= image_tag("package.png", alt: "package") %></div>
            <div class="package_data">
              <div class="package_name"><b><%= p[0] %></b></div>
              <div class="package_settings"><%= t(:minimum_quantity, scope: 'locale.messages.package') %>: <%= p[1].minimum_quantity %></div>
              <div class="package_settings"><%= t(:maximum_quantity, scope: 'locale.messages.package') %>: <%= p[1].maximum_quantity %></div>
              <div class="package_settings"><%= t(:width, scope: 'locale.messages.package') %>: <%= p[1].width*',' %></div>
              <div class="package_settings"><%= t(:height, scope: 'locale.messages.package') %>: <%= p[1].height*',' %></div>
              <div class="package_settings"><%= t(:length, scope: 'locale.messages.package') %>: <%= p[1].length*',' %></div>
              <div class="package_material"><%= t(:material, scope: 'locale.messages.package') %>: <%= p[1].material*',' %></div>
            </div>
          <% end %>
        <% end %>
      </div>
      <%= yield %>
<%= render "layouts/footer" %>

app/views/home/login.html.erb
<%= render "layouts/header" %>
<nav class="navbar navbar-expand-lg " color-on-scroll="500">
  <div class="container-fluid">
    <div class="collapse navbar-collapse justify-content-end" id="navigation">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if @logged_in %>
            <%= link_to t(:logout, scope: 'locale.messages'), home_logout_path %>
          <% else %>
            <%= link_to t(:login, scope: 'locale.messages'), home_login_path %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>
<!-- End Navbar -->
<div class="content">
  <div class="container-fluid">
    <div class="row">
      <% if @logged_in %>
      <div class="col-md-11">
        <div class="card" style="max-width: 50%">
          <div class="card-header">
            <h4 class="card-title"><%= t(:logout, scope: 'locale.messages') %></h4>
          </div>
          <div class="card-body">
            <form>
              <a href="logout" class="btn btn-info btn-fill pull-right"><%= t(:logout, scope: 'locale.messages') %></a>
              <div class="clearfix"></div>
              <div class="register-account">
                <%= t(:already_signed_in, scope: 'locale.messages') %>
              </div>
            </form>
          </div>
        </div>
      </div>
      <% else %>
      <div class="col-md-11">
        <div class="card" style="max-width: 50%">
          <div class="card-header">
            <h4 class="card-title"><%= t(:login, scope: 'locale.messages') %></h4>
          </div>
          <div class="card-body">
            <form>
              <div class="row">
                <div class="col-md-6 pr-1">
                  <div class="form-group">
                    <label>Email</label>
                    <input type="email" class="form-control" id="login-email" placeholder="<%= t(:login_from_email_placeholder, scope: 'locale.messages') %>" value="">
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-4 pr-1">
                  <div class="form-group">
                    <label><%= t(:password, scope: 'locale.messages') %></label>
                    <input type="password" class="form-control" id="login-password" placeholder="<%= t(:login_from_password_placeholder, scope: 'locale.messages') %>" value="">
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-info btn-fill pull-right" id="btnSubmit"><%= t(:login, scope: 'locale.messages') %></button>
              <div class="clearfix"></div>
              <div class="register-account">
                <%= t(:login_form_register, scope: 'locale.messages') %> <%= link_to t(:register, scope: 'locale.messages'), home_register_path %>
              </div>
            </form>
          </div>
        </div>
      </div>
      <% end %>
      <script>
      $(document).ready(function () {
        $("#btnSubmit").click(function (event) {
          var email = $('#login-email').val();
          var password = $('#login-password').val();
          customerAuthorizationScope.loginFunction.send(email, password);
        });
      });
      </script>
<%= render "layouts/footer" %>