config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/login'
  get 'home/logout'
  get 'home/register'
  get 'application/client_authorization'

  resources :offers, only: %i[index show] do
    post '/accept', to: 'offers#accept', :on => :member
    post '/reject', to: 'offers#reject', :on => :member
  end

  resources :customers, only: %i[show create new update edit]
  resources :products, only: %i[index]

  namespace :rest do
    resources :offers, only: [] do
      resources :products, only: %i[index show create]
    end

    resources :products, only: [] do
      resources :type_attributes, only: %i[index show create]
    end

    resources :users, param: :id, only: %i[index show create]
    resources :customers, param: :id, only: %i[index show create] do
      resources :offers, only: %i[index show create]
      post 'offers/:id/accept', to: 'offers#accept'
      post 'offers/:id/reject', to: 'offers#reject'
    end
  end
    post '/auth/login_user', to: 'authentication#login_user'
    post '/auth/login_customer', to: 'authentication#login_customer'
end

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
  <%= display_flash(key, value) %>

  <script>
    $(function() {
      closeFlash();
    });
  </script>

<% end %>

app/views/layouts/_footer.html.erb
    </div>
      </div>
      </div>
        <footer class="footer">
          <div class="container-fluid">
            <nav>
              <ul class="footer-menu">
                <li>
                  <%= link_to t(:main, scope: 'locale.messages.sidebar'), root_path %>
                </li>
                <li>
                  <% if @logged_in && @customer.present? %>
                    <%= link_to t(:customer_profile, scope: 'locale.messages.profile'), edit_customer_path(@customer) %>
                  <% else %>
                    <%= link_to t(:customer_profile, scope: 'locale.messages.profile'), home_login_path %>
                  <% end %>
                </li>
              </ul>
              <p class="copyright text-center">
                © 2021
                <a href="https://syngress.pl">Syngress Network</a>, pack manager demo
              </p>
            </nav>
          </div>
        </footer>
      </div>
    </div>
  </body>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <title>Pack Manager</title>
  <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no' name='viewport' />
  <%= favicon_link_tag asset_path('favicon.ico') %>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <div class="wrapper">
    <div class="sidebar" data-color="blue">
      <div class="sidebar-wrapper">
        <div class="logo">
          <a href="/" class="simple-text">
            Pack Manager
          </a>
        </div>
        <ul class="nav">
          <% if @logged_in && @customer.present? %>
            <li class="<%= 'nav-item active' if current_page?(root_path) %>">
              <a class="nav-link" href="<%= root_path %>">
                <%= image_tag("home.png", alt: "home", style: 'height:20px;width:20px;margin-right: 10px;') %>
                <p><%= t(:main, scope: 'locale.messages.sidebar') %></p>
              </a>
            </li>
            <li class="<%= 'nav-item active' if current_page?(edit_customer_path(@customer)) %>">
              <a class="nav-link" href="<%= edit_customer_path(@customer) %>">
                <%= image_tag("profile_sidebar.png", alt: "profile", style: 'height:20px;width:20px;margin-right: 10px;') %>
                <p><%= t(:profile, scope: 'locale.messages.sidebar') %></p>
              </a>
            </li>
            <li class="<%= 'nav-item active' if current_page?(products_path) %>">
              <a class="nav-link" href="<%= products_path %>">
                <%= image_tag("product_sidebar.png", alt: "product", style: 'height:20px;width:20px;margin-right: 10px;') %>
                <p><%= t(:products, scope: 'locale.messages.sidebar') %></p>
              </a>
            </li>
            <li class="<%= 'nav-item active' if current_page?(offers_path) %>">
              <a class="nav-link" href="<%= offers_path %>">
                <%= image_tag("offer_sidebar.png", alt: "offers", style: 'height:23px;width:23px;margin-right: 10px;') %>
                <p><%= t(:offers, scope: 'locale.messages.sidebar') %></p>
              </a>
            </li>
          <% else %>
            <li class="<%= 'nav-item active' if current_page?(root_path) %>">
              <a class="nav-link" href="<%= root_path %>">
                <%= image_tag("home.png", alt: "home", style: 'height:20px;width:20px;margin-right: 10px;') %>
                <p><%= t(:main, scope: 'locale.messages.sidebar') %></p>
              </a>
            </li>
            <li>
              <a class="nav-link" href="<%= home_login_path %>">
                <%= image_tag("profile_sidebar.png", alt: "profile", style: 'height:20px;width:20px;margin-right: 10px;') %>
                <p><%= t(:profile, scope: 'locale.messages.sidebar') %></p>
              </a>
            </li>
            <li>
              <a class="nav-link" href="<%= home_login_path %>">
                <%= image_tag("product_sidebar.png", alt: "product", style: 'height:20px;width:20px;margin-right: 10px;') %>
                <p><%= t(:products, scope: 'locale.messages.sidebar') %></p>
              </a>
            </li>
            <li>
              <a class="nav-link" href="<%= home_login_path %>">
                <%= image_tag("offer_sidebar.png", alt: "offers", style: 'height:23px;width:23px;margin-right: 10px;') %>
                <p><%= t(:offers, scope: 'locale.messages.sidebar') %></p>
              </a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="main-panel">
    <div id='flash' class='flex-column'>
      <%= render partial: 'layouts/flash'  %>
    </div>

<!-- Navbar -->